apiVersion: apps/v1 # New api version
kind: Deployment # New kind
metadata:
  name: nginx-deployment
  labels:
    purpose: nginx-single-deployment-demo
    app: nginx
spec:
  replicas: 5 # tells deployment to run 1 pods matching the template
  # selector is used to 'select' the template to use based on labels
  selector:
    matchLabels:
      app: nginx # match with at least one label in template
  # create pods using pod definition in this template
  # template to use to create Pod/Containers (note that selector match the label)
  template:
    metadata:
      labels:
        app: nginx
        description: another-random-label
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 256Mi
            cpu: "0.2"
          limits:
            memory: 512Mi
            cpu: "0.5"

