include:
  - local: 'my_build.yaml'
  - local: 'my_push.yaml'


stages:
  - stage1
  - stage2


default:
  image: docker
  tags:
    - YOUR RUNNER
  before_script:
    - echo "this is before script"
  after_script:
    - echo "this is after script"
