apiVersion: v1
kind: Pod
metadata:
  name: multiple-app
  labels:
    purpose: nginx-and-redis-multiple-container-demo
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: 256Mi
        cpu: "0.2"
      limits:
        memory: 512Mi
        cpu: "0.5"
        
  - name: redis
    image: redis
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 6379
    resources:
      requests:
        memory: 256Mi
        cpu: "0.2"
      limits:
        memory: 512Mi
        cpu: "0.5"