apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: debian
    # main entrypoint for args
    command: ["printenv"]
    # parameters for the command
    args: ["HOSTNAME", "KUBERNETES_PORT"]
    resources:
      requests:
        memory: 256Mi
        cpu: "0.2" 
      limits:
        memory: 512Mi
        cpu: "0.5"